// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/search-profiles.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-profiles.ts
var search_profiles_default = defineTool({
  name: "search_profiles",
  title: "Search profiles",
  description: "Search Hyliya user profiles by username, display name, or location keyword. Returns public profile info only.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Search keyword (matches username, display name, or location)."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = supabaseAnon();
    const q = query.replace(/[%_,()]/g, "");
    const { data, error } = await supabase.from("profiles").select("id, username, display_name, bio, age, gender, location, avatar_url, is_premium").or(`username.ilike.%${q}%,display_name.ilike.%${q}%,location.ilike.%${q}%`).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { profiles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_profile_default = defineTool2({
  name: "get_profile",
  title: "Get profile",
  description: "Get a Hyliya public profile by user id or username.",
  inputSchema: {
    id: z2.string().optional().describe("User UUID."),
    username: z2.string().optional().describe("Username (used if id is not provided).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, username }) => {
    if (!id && !username) {
      return { content: [{ type: "text", text: "Provide either id or username." }], isError: true };
    }
    const supabase = supabaseAnon();
    let query = supabase.from("profiles").select("id, username, display_name, bio, age, gender, location, avatar_url, album, is_premium, created_at").limit(1);
    query = id ? query.eq("id", id) : query.eq("username", username);
    const { data, error } = await query.maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Profile not found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-recent-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_posts_default = defineTool3({
  name: "list_recent_posts",
  title: "List recent posts",
  description: "List recent public timeline posts on Hyliya.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of posts (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("timeline_posts").select("id, user_id, content, media_urls, hashtags, likes_count, comments_count, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hyliya-mcp",
  title: "Hyliya MCP",
  version: "0.1.0",
  instructions: "Tools for Hyliya (AI dating & chat). Use `search_profiles` to find users, `get_profile` for details, and `list_recent_posts` for the public timeline.",
  tools: [search_profiles_default, get_profile_default, list_recent_posts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
