// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oeepmsbttxfknkznbnym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZXBtc2J0dHhma25rem5ibnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4ODQwMjMsImV4cCI6MjA2NTQ2MDAyM30.U0ur6BLFqhRJgcqTXGWgdqsWXwryQGw7YcMQp9XT364";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);